account_usage:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qpb58754.us-east-1
      user: venlete
      role: SYSADMIN

      # Keypair config
      private_key_path: /Users/evenlet/.ssh/rsa_key.p8
      # or private_key instead of private_key_path

      database: DBT_DEMO_DB
      warehouse: COMMON_XS
      schema: ACCOUNT_USAGE
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qpb58754.us-east-1
      user: venlete
      role: SYSADMIN

      # Keypair config
      private_key_path: /Users/evenlet/.ssh/rsa_key.p8
      # or private_key instead of private_key_path

      database: DBT_DEMO_DB
      warehouse: COMMON_XS
      schema: JAFFLE_SHOP
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false